### PR TITLE
Sample pgloader script

### PR DESCRIPTION
**Pull request by talos**
Add a sample pgloader script to import all the data, with BBLs and years, into a single postgres table (in this case, one living in a docker4data table.)

### CODE REVIEW

**Comment by clhenrick** [comment]
thanks @talos! Is there anyway we can make the [settings for the db path](https://github.com/talos/dhcr-rent-stabilized-data/blob/87570b51db5da6513cd74d74fd639df0737a73d0/pgloader.load#L6) variables with pg loader? That way one could load them into a db on their local system?

**Comment by talos** [comment]
No problem @clhenrick .  If we're less specific about the path (not specifying localhost or port) it will default to the most common postgres setup (port 5432, unix socket.)

However, I'm not sure of any way with pgloader to feed in values for that outside of the `pgloader.load` file.  The documentation is also a little all over the place. :/

**Comment by clhenrick** [comment]
Will pgloader recognize bash env variables? Don't have time to test at the moment but can later.

This seems promising: http://www.postgresql.org/docs/9.3/static/libpq-envars.html

and this: http://www.postgresql.org/docs/9.4/static/plpgsql-declarations.html

**Comment by talos** [comment]
@clhenrick best. links. ever.

Using the new, ambiguous `pgloader.load`, the following command would load into a docker4data DB:

```
PGUSER=postgres PGDATABASE=postgres PGHOST=localhost PGPORT=54321 PGPASSWORD=docker4data pgloader pgloader.load
```

Obviously, you can swap in whatever other values for your DB.

Ready to merge?

**Comment by clhenrick** [comment]
:+1:  :8ball:  :100:

**Pull request merged**
